sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y python-virtualenv
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-h5py
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y python-matplotlib
install:
  - sudo pip install codecov
script:
  - make -f Makefile test
after_success:
  - codecov
deploy:
  provider: pypi
  user: juanchopanza
  password:
    secure: fLcTXIjrPUhYsmXFshtzfO/V/QWQprxJ68KA9fxayzmpLHoqX6C0sl7PAmPosXempMCBqntjJ4k7IDGyOdaBx+igmHcylqFcmiFSgeFYjOTqcMCLsBEaqFIutqoMTPT+/OiM6YDJFxNTwuO41uI5i4lE1pKV9XZqKh/pmJYluNQ=
  on:
    tags: true
    branch: master
