language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy
  - sudo apt-get install python-h5py
install:
  - pip install --upgrade pip
  - pip install --ignore-installed -r requirements_dev.txt
  - pip install matplotlib==1.3.1
  - pip install .
cache:
  directories:
    - $HOME/.cache/pip
script:
  - make -f Makefile.travis_ci test
