sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y python-virtualenv
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-h5py
  - sudo pip install scipy==0.17
  - sudo apt-get install -y python-matplotlib
script:
  - make -f Makefile test
after_success:
  - sudo pip install codecov
  - codecov
before_deploy:
  - sudo pip install twine
deploy:
  provider: pypi
  user: bbp.opensource
  password:
    secure: N/2AGpTUSOGOxQqYulja5Etj228w1SByVuX+ozPvuPJTm5kJh5fqav8FVtPLziaWAaWxJ6W2nFdWT9AwodwMk3+1NBHMWpOZ3NJnvibz0cvYCkXdNcgXOFGrPSeX3Oo2d74IeT20R44lieZEW62j4488SSaVkwr3p7YgyfVMVGo=
  on:
    tags: true
    branch: master
